/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.DBAseguradora;
import java.awt.Color;
import vista.TBBANCO.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author usuario
 */
public class Aseguradoramiento extends javax.swing.JFrame {
    connection C=new connection();
    Connection AS=C.conexiondb();
    PreparedStatement ps=null;
    ResultSet re=null;
    /**
     * Creates new form Aseguradora
     */
    public Aseguradoramiento() {
        initComponents();
         Cargartablas();
         Cargarcombox();
         
         jComboBox2.addItem("Seleccione");
         jComboBox2.addItem("Vencido");
         jComboBox2.addItem("Activo");
        // this.getContentPane().setBackground(Color.);

    }

public void Cargartablas(){
    DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("Codigo");
        tabla.addColumn("Fecha de aseguramiento");
        tabla.addColumn("fecha de expiracion");
        tabla.addColumn("valor");
        tabla.addColumn("estado");
        tabla.addColumn("costo");
        tabla.addColumn("placa");
        
       
        
        tablaconsulta.setModel(tabla);
        String datos[]=new String[9];
        try{
            ps=AS.prepareStatement("SELECT*FROM aseguramiento");
            re=ps.executeQuery();
            while(re.next()){
                datos[0]=re.getString(1);
                datos[1]=re.getString(2);
                datos[2]=re.getString(3);
                datos[3]=re.getString(4);
                datos[4]=re.getString(5);
                datos[5]=re.getString(6);
                datos[6]=re.getString(7);
                
                tabla.addRow(datos);
                
            }
        }
        catch (Exception e){
            System.out.print(e);
            
        }
}
 
    public void Registrar(){
    try{
    
    ps=AS.prepareStatement("INSERT INTO aseguramiento(asecodigo,asefechainicio,asefechaexpiracion,asevaloraseguradora,aseestado,asecosto,aseplaca) values (?,?,?,?,?,?,?)");
    ps.setInt(1,Integer.parseInt(jTextCodi.getText()));
    ps.setString(2,jTextFI.getText());
    ps.setString(3,jTextFE.getText());
    ps.setInt(4,Integer.parseInt(jTextVal.getText()));
    ps.setString(5,jComboBox2.getSelectedItem().toString());
    ps.setInt(6,Integer.parseInt(jTexConst.getText()));
    ps.setString(7,jComboBox1.getSelectedItem().toString());

    
  
    
   
    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
    public void Eliminar(String dat){
        try{
        ps=AS.prepareStatement("DELETE FROM aseguramiento where asecodigo ='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
        }
       public void Modificar(String  cod,String fi,String fe,String val,String est,String cos,String pla){
        try{
            ps=AS.prepareStatement("UPDATE aseguramiento SET  asecodigo='"+ cod +"', asefechainicio='"+fi+"',asefechaexpiracion='"+fe+"',asevaloraseguradora='"+val+"',aseestado='"+est+"',asecosto='"+cos+"' where aseplaca='"+pla+"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    }
       
       public void Cargarcombox(){
    try{
        jComboBox1.removeAll();
        jComboBox1.addItem("Seleccione ");
        ps=AS.prepareStatement("SELECT autoplaca  FROM  automotores");
        re=ps.executeQuery();
        while(re.next()){
            String aux=re.getString("autoplaca");
            this.jComboBox1.addItem(aux);
        }
    }
    catch(Exception e){
        
        
    }
   
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextCodi = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFE = new javax.swing.JTextField();
        jTextFI = new javax.swing.JTextField();
        jTextVal = new javax.swing.JTextField();
        jTexConst = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBuModifi = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 113, 209));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 900, 180));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Fecha de expiracion");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Fecha   de inicio");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Codigo Aseguradora");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Valor ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Costo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Estado");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Placa");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        getContentPane().add(jTextCodi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 128, 28));

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jButton7.setText("Registrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));
        getContentPane().add(jTextFE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 128, 28));
        getContentPane().add(jTextFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 128, 28));
        getContentPane().add(jTextVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 128, 28));
        getContentPane().add(jTexConst, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 128, 28));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 99, 28));

        jBuModifi.setText("Modificar");
        jBuModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuModifiActionPerformed(evt);
            }
        });
        getContentPane().add(jBuModifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, 30));

        jLabel8.setBackground(new java.awt.Color(102, 255, 255));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextCodi.setText(null);
        jTextFI.setText(null);
        jTextFE.setText(null);
        jTextVal.setText(null);
        jComboBox2.removeAllItems();
        jTexConst.setText(null);
        jComboBox1.removeAllItems();
       Cargarcombox();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String dat=jTextCodi.getText();
        Eliminar(dat);
        Cargartablas();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Registrar();
        Cargartablas();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ASE a=new ASE();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBuModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuModifiActionPerformed
        String  cod,fi,fe, val,est,cos, pla;
        pla=jComboBox1.getSelectedItem().toString();
        cod=jTextCodi.getText();
        fi=jTextFI.getText();
        fe=jTextFE.getText();
        val=jTextVal.getText();
        est=jComboBox2.getSelectedItem().toString();
        cos=jTexConst.getText();
    
        Modificar(cod, fi, fe, val, est, cos, pla);
        Cargartablas();
    }//GEN-LAST:event_jBuModifiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aseguradoramiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aseguradoramiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aseguradoramiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aseguradoramiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aseguradoramiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuModifi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexConst;
    private javax.swing.JTextField jTextCodi;
    private javax.swing.JTextField jTextFE;
    private javax.swing.JTextField jTextFI;
    private javax.swing.JTextField jTextVal;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables
}
