/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.DBAseguradora;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author usuario
 */
public class automotores extends javax.swing.JFrame {
 connection Ca=new connection();
    Connection AS=Ca.conexiondb();
    PreparedStatement ps=null;
    ResultSet re=null;
    /**
     * Creates new form automotores
     */
    public automotores() {
        initComponents();
        Cargartablas();
    }

public void Cargartablas(){
    DefaultTableModel tabla=new DefaultTableModel();
        tabla.addColumn("Placa");
        tabla.addColumn("Marca");
        tabla.addColumn("Tipo");
        tabla.addColumn("Modelo");
        tabla.addColumn("Numero pasajeros");
        tabla.addColumn("Cilindraje");
        tabla.addColumn("Chasis");
        
       
        
        tablaconsulta.setModel(tabla);
        String datos[]=new String[9];
        try{
            ps=AS.prepareStatement("SELECT*FROM automotores");
            re=ps.executeQuery();
            while(re.next()){
                datos[0]=re.getString(1);
                datos[1]=re.getString(2);
                datos[2]=re.getString(3);
                datos[3]=re.getString(4);
                datos[4]=re.getString(5);
                datos[5]=re.getString(6);
                datos[6]=re.getString(7);
                
                tabla.addRow(datos);
                
            }
        }
        catch (Exception e){
            System.out.print(e);
            
        }
}

public void Registrar(){
    try{
    
    ps=AS.prepareStatement("INSERT INTO automotores (autoplaca,automarca,autotipo,automodel,autonumpasajeros,autocilindraje,autonumchasis) VALUES (?,?,?,?,?,?,?)");
    ps.setString(1,jTextPlaca.getText());
    ps.setString(2,jTextMARCA.getText());
    ps.setString(3,jComboBox1.getSelectedItem().toString());
    ps.setString(4,jTexMODEL.getText());
    ps.setString(5,jTextNP.getText());
    ps.setString(6,jTextCILIN.getText());
    ps.setString(7,jTextNumerChasis.getText());


    ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos guardados");
    }
    catch (Exception e){
    System.out.print("es " + e);
    }
}
public void Eliminar(String dat){
        try{
        ps=AS.prepareStatement("DELETE FROM automotores where  autoplacac='"+dat+"' ");
        ps.executeUpdate();
        JOptionPane.showMessageDialog(null,"Datos eliminados");
        }
            catch(Exception e){
                    System.out.print(e);
                    }
     }
       public void Cargarcombox(){
    try{
        jComboBox1.removeAll();
        jComboBox1.addItem("Seleccione tipo ");
        ps=AS.prepareStatement("SELECT auttipo  FROM  tipoautomotores");
        re=ps.executeQuery();
        while(re.next()){
            String aux=re.getString("auttipo");
            this.jComboBox1.addItem(aux);
        }
    }
    catch(Exception e){
        
        
    }
   
}
       public void Modificar(String  aut,String tip,String mod,String pasa,String cili,String cha,String pla){
        try{
            ps=AS.prepareStatement("UPDATE automotores SET  automarca='" +aut+"',autotipo='"+ tip+"',automodel='"+ mod+"',autonumpasajeros='" +pasa+"',autocilindraje='" +cili+"',autonumchasis='"+ cha+"'where autoplaca='"+pla+"' ");
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null,"Datos Modificados");
        }
        catch(Exception e){
            
            System.out.print( e);
        }
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaconsulta = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextPlaca = new javax.swing.JTextField();
        jTextMARCA = new javax.swing.JTextField();
        jTexMODEL = new javax.swing.JTextField();
        jTextNP = new javax.swing.JTextField();
        jTextCILIN = new javax.swing.JTextField();
        jTextNumerChasis = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBuModifi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaconsulta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 750, 180));

        jButton7.setText("Registrar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 70, -1));

        jButton5.setText("Limpiar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jButton1.setText("ATRAS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 14, 50, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Marca");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Numero de Pasajeros");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Modelo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 104, -1, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 75, 46, 12));

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cilindraje");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Numero de  chasis");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        jTextPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 11, 110, -1));

        jTextMARCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextMARCAActionPerformed(evt);
            }
        });
        getContentPane().add(jTextMARCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 37, 110, -1));

        jTexMODEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexMODELActionPerformed(evt);
            }
        });
        getContentPane().add(jTexMODEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 101, 110, -1));

        jTextNP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNPActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 110, -1));

        jTextCILIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCILINActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCILIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 110, -1));

        jTextNumerChasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNumerChasisActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNumerChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 110, -1));

        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 75, 110, -1));

        jBuModifi.setText("Modificar");
        jBuModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuModifiActionPerformed(evt);
            }
        });
        getContentPane().add(jBuModifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/automotor.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 840, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Registrar();
        Cargartablas();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String dat=jTextPlaca.getText();
        Eliminar(dat);
        Cargartablas();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextPlaca.setText(null);
        jTextMARCA.setText(null);
        jComboBox1.removeAllItems();
        jTexMODEL.setText(null);
        jTextNP.setText(null);
        jTextCILIN.setText(null);
        jTextNumerChasis.setText(null);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ASE a=new ASE();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPlacaActionPerformed

    private void jTextMARCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextMARCAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextMARCAActionPerformed

    private void jTexMODELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexMODELActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexMODELActionPerformed

    private void jTextNPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNPActionPerformed

    private void jTextCILINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCILINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCILINActionPerformed

    private void jTextNumerChasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNumerChasisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNumerChasisActionPerformed

    private void jBuModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuModifiActionPerformed
        String  aut,tip, mod, pasa,cili, cha, pla;
        aut=jTextMARCA.getText();

        tip=jComboBox1.getSelectedItem().toString();
        mod=jTexMODEL.getText();
        pasa=jTextNP.getText();
        cili=jTextCILIN.getText();
        cha=jTextNumerChasis.getText();
        pla=jTextPlaca.getText();

        Modificar (aut, tip, mod, pasa, cili, cha, pla);
        Cargartablas();
    }//GEN-LAST:event_jBuModifiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(automotores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(automotores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(automotores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(automotores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new automotores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuModifi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTexMODEL;
    private javax.swing.JTextField jTextCILIN;
    private javax.swing.JTextField jTextMARCA;
    private javax.swing.JTextField jTextNP;
    private javax.swing.JTextField jTextNumerChasis;
    private javax.swing.JTextField jTextPlaca;
    private javax.swing.JTable tablaconsulta;
    // End of variables declaration//GEN-END:variables
}
